name: Python Performance Test
env:
    PYTHONPATH: $PYTHONPATH:mydjangoproject
    DJANGO_SETTINGS_MODULE: mydjangoproject.settings
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        pip install --upgrade pytest-benchmark
        pip install django
        pip install pytest pytest-django    


    - name: Run benchmark tests
      run:
        pytest --benchmark-autosave --benchmark-sort=mean --benchmark-compare --benchmark-columns=min,max,mean,stddev --benchmark-histogram --benchmark-json=.benchmark/benchmark_results.json
    - name: Generate benchmark report
      run: pytest-benchmark compare --compare-with=.benchmark/previous_benchmark_results.json --json=.benchmark/benchmark_results.json
      env:
        PYTEST_BENCHMARK_COMPARE_FILE: .benchmark/previous_benchmark_results.json
      

