name: Python Application Tests
env:
    PYTHONPATH: $PYTHONPATH:mydjangoproject
    DJANGO_SETTINGS_MODULE: mydjangoproject.settings
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |

        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python mydjangoproject/manage.py migrate
        pip install pytest-cov
        pip install pytest
        pip install pytest pytest-django
        pip install django
        pip install coverage
        
    - name: Run tests
      run: |
        coverage run -m pytest
    - name: Generate coverage report
      run: |
        coverage report
