name: Python Mutation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    env:
        PYTHONPATH: $mydjangoproject
        DJANGO_SETTINGS_MODULE: mydjangoproject.settings
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |

        python -m pip install --upgrade pip
        pip install mutmut
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest pytest-django
        pip install django

    - name: Run mutation tests
      run: mutmut run --paths-to-mutate=test_num.py,mydjangoproject/mydjangoapp/test_models.py,mydjangoproject/mydjangoapp/test_views.py --tests-dir=test_num.py,mydjangoproject/mydjangoapp 
