name: Python Unittests Workflow

on: [push, pull_request]

jobs:
  test:
    name: Test with Python unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      
      - name: Run unittests
        run: python -m unittest discover
